package com.justaleks.syncnotes.data

import android.content.Context
import androidx.credentials.CredentialManager
import androidx.credentials.GetCredentialRequest
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.firebase.auth.AuthCredential
import com.google.firebase.auth.GoogleAuthProvider
import com.justaleks.syncnotes.R

/**
 * Google sign-in on Android does not use the web OAuth redirect. Credential Manager
 * asks the device which Google accounts are signed in, and Google validates the
 * request against this app's package name and signing certificate — which is why the
 * SHA-1 fingerprint has to be registered in the Firebase console for any of this to
 * work. The token that comes back is then exchanged for a Firebase credential.
 */
object GoogleSignIn {

    /**
     * `default_web_client_id` is generated by the google-services plugin from the
     * `client_type: 3` entry in google-services.json. It is the *web* client id on
     * purpose: it identifies the backend the token is minted for, not this app.
     */
    private fun serverClientId(context: Context) = context.getString(R.string.default_web_client_id)

    /**
     * Shows the account picker and returns a Firebase credential. Kept separate from
     * signing in so the same flow can either sign in or link to an existing account.
     *
     * [context] must be an Activity — Credential Manager needs somewhere to show UI.
     */
    suspend fun requestCredential(context: Context): AuthCredential {
        val option = GetGoogleIdOption.Builder()
            // false so the picker still offers accounts that have never used this app,
            // otherwise a first-time user is shown an empty list.
            .setFilterByAuthorizedAccounts(false)
            .setServerClientId(serverClientId(context))
            .build()

        val request = GetCredentialRequest.Builder().addCredentialOption(option).build()
        val response = CredentialManager.create(context).getCredential(context, request)

        val googleCredential = GoogleIdTokenCredential.createFrom(response.credential.data)
        return GoogleAuthProvider.getCredential(googleCredential.idToken, null)
    }
}
